name: C++ CI

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        # - name: Setup C++
        #   uses: aminya/setup-cpp@v1
        #   with:
        #     compiler: 'gcc'

        - name: Compile
          run: g++ -I ./ *.cpp
        
        - name: Install Valgrind
          run: sudo apt-get install valgrind

        - name: Run Valgrind
          run: |
            valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=valgrind.rpt ./a.out
            cat valgrind.rpt

        - name: Archive production artifacts
          uses: actions/upload-artifact@v2
          with:
            name: valgrind-report
            path: valgrind.rpt