# Create a GitHub Actions Workflow
# I want you to compile this c++ program
# I want you to use valgrind as a wrapper for running the binary and perform stress testing
# I want you to get the valgrind.rpt file outputed from valgrind saved as an artifact

name: C++ CI

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Setup C++
            uses: actions/setup-cpp@v1
            with:
                cpp-version: 'latest'

        - name: Compile
            run: g++ -o program program.cpp

        - name: Run Valgrind
            run: valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=valgrind.rpt ./program

        - name: Archive production artifacts
            uses: actions/upload-artifact@v2
            with:
                name: valgrind-report
                path: valgrind.rpt